/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import form.cinemaHall.FrmCinemaHall;
import form.cinemaHall.FrmSearchHalls;
import form.member.FrmMember;
import form.member.FrmSearchMembers;
import form.movie.FrmMovie;
import form.movie.FrmSearchMovies;
import form.projection.FrmNewProjectionList;
import form.reservation.FrmReservation;
import javax.swing.JDialog;
import javax.swing.JFrame;
import session.Session;
import usecase.UseCase;

/**
 *
 * @author Vladan Simonovic
 */
public class FrmMainLandscape extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMainLandscape() {
        initComponents();
        setCurrentUser();
        maximizeForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurrentUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jmb = new javax.swing.JMenuBar();
        jmMovie = new javax.swing.JMenu();
        jmiAddNewMovie = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSearchMovies = new javax.swing.JMenuItem();
        jmCinemaHall = new javax.swing.JMenu();
        jmiAddNewHall = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiSearchHalls = new javax.swing.JMenuItem();
        jmMember = new javax.swing.JMenu();
        jmiNewMember = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiSearchMembers = new javax.swing.JMenuItem();
        jmProjection = new javax.swing.JMenu();
        jmiNewProjectionList = new javax.swing.JMenuItem();
        jmReservation = new javax.swing.JMenu();
        jmiNewReservations = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinema - Main form");

        lblCurrentUser.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        lblCurrentUser.setForeground(new java.awt.Color(255, 255, 255));
        lblCurrentUser.setOpaque(true);
        getContentPane().add(lblCurrentUser, java.awt.BorderLayout.CENTER);

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/resources/landscape.jpg"))); // NOI18N
        jLabel2.setText("Current user:");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jmMovie.setText("Movie");

        jmiAddNewMovie.setText("Add new movie...");
        jmiAddNewMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewMovieActionPerformed(evt);
            }
        });
        jmMovie.add(jmiAddNewMovie);
        jmMovie.add(jSeparator1);

        jmiSearchMovies.setText("Search movies...");
        jmiSearchMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSearchMoviesActionPerformed(evt);
            }
        });
        jmMovie.add(jmiSearchMovies);

        jmb.add(jmMovie);

        jmCinemaHall.setText("Cinema Hall");

        jmiAddNewHall.setText("Add new hall...");
        jmiAddNewHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewHallActionPerformed(evt);
            }
        });
        jmCinemaHall.add(jmiAddNewHall);
        jmCinemaHall.add(jSeparator2);

        jmiSearchHalls.setText("Search halls...");
        jmiSearchHalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSearchHallsActionPerformed(evt);
            }
        });
        jmCinemaHall.add(jmiSearchHalls);

        jmb.add(jmCinemaHall);

        jmMember.setText("Member");

        jmiNewMember.setText("New member...");
        jmiNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewMemberActionPerformed(evt);
            }
        });
        jmMember.add(jmiNewMember);
        jmMember.add(jSeparator3);

        jmiSearchMembers.setText("Search members...");
        jmiSearchMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSearchMembersActionPerformed(evt);
            }
        });
        jmMember.add(jmiSearchMembers);

        jmb.add(jmMember);

        jmProjection.setText("Projection");

        jmiNewProjectionList.setText("Add projection list...");
        jmiNewProjectionList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewProjectionListActionPerformed(evt);
            }
        });
        jmProjection.add(jmiNewProjectionList);

        jmb.add(jmProjection);

        jmReservation.setText("Reservation");

        jmiNewReservations.setText("Add new reservations...");
        jmiNewReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewReservationsActionPerformed(evt);
            }
        });
        jmReservation.add(jmiNewReservations);

        jmb.add(jmReservation);

        setJMenuBar(jmb);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAddNewMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewMovieActionPerformed
//        FrmMovie frmMovie = new FrmMovie(this, true, FrmMode.NEW);
//        frmMovie.setVisible(true);
//
//        Session.getInstance().setCurrentUseCase(UseCase.UC_NEW_MOVIE);

    }//GEN-LAST:event_jmiAddNewMovieActionPerformed

    private void jmiSearchMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSearchMoviesActionPerformed
        JDialog dialog = new JDialog(this, "Cinema - search movies", true);
        FrmSearchMovies frmSearchMovies = new FrmSearchMovies();

        dialog.add(frmSearchMovies);
        dialog.pack();

        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiSearchMoviesActionPerformed

    private void jmiAddNewHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewHallActionPerformed
        FrmCinemaHall frmCinemaHall = new FrmCinemaHall(this, true, FrmMode.NEW);
        frmCinemaHall.setVisible(true);

        Session.getInstance().setCurrentUseCase(UseCase.UC_NEW_CINEMA_HALL);
    }//GEN-LAST:event_jmiAddNewHallActionPerformed

    private void jmiSearchHallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSearchHallsActionPerformed
        JDialog dialog = new JDialog(this, "Cinema - search movies", true);
        FrmSearchHalls frmSearchHalls = new FrmSearchHalls();

        dialog.add(frmSearchHalls);
        dialog.pack();

        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiSearchHallsActionPerformed

    private void jmiNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewMemberActionPerformed
        FrmMember frmMember = new FrmMember(this, true, FrmMode.NEW);
        frmMember.setVisible(true);

        Session.getInstance().setCurrentUseCase(UseCase.UC_NEW_MEMBER);

    }//GEN-LAST:event_jmiNewMemberActionPerformed

    private void jmiSearchMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSearchMembersActionPerformed
        JDialog dialog = new JDialog(this, "Cinema - search members", true);
        FrmSearchMembers frmSearchMembers = new FrmSearchMembers();

        dialog.add(frmSearchMembers);
        dialog.pack();

        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiSearchMembersActionPerformed

    private void jmiNewProjectionListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewProjectionListActionPerformed
        FrmNewProjectionList frmNewProjectionList = new FrmNewProjectionList(this, true);
        frmNewProjectionList.setTitle("New projection list");
        frmNewProjectionList.setVisible(true);
    }//GEN-LAST:event_jmiNewProjectionListActionPerformed

    private void jmiNewReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewReservationsActionPerformed
        FrmReservation frmReservation = new FrmReservation(this, true);
        frmReservation.setTitle("New reservations list");
        frmReservation.setVisible(true);
        
    }//GEN-LAST:event_jmiNewReservationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu jmCinemaHall;
    private javax.swing.JMenu jmMember;
    private javax.swing.JMenu jmMovie;
    private javax.swing.JMenu jmProjection;
    private javax.swing.JMenu jmReservation;
    private javax.swing.JMenuBar jmb;
    private javax.swing.JMenuItem jmiAddNewHall;
    private javax.swing.JMenuItem jmiAddNewMovie;
    private javax.swing.JMenuItem jmiNewMember;
    private javax.swing.JMenuItem jmiNewProjectionList;
    private javax.swing.JMenuItem jmiNewReservations;
    private javax.swing.JMenuItem jmiSearchHalls;
    private javax.swing.JMenuItem jmiSearchMembers;
    private javax.swing.JMenuItem jmiSearchMovies;
    private javax.swing.JLabel lblCurrentUser;
    // End of variables declaration//GEN-END:variables

    private void setCurrentUser() {
        lblCurrentUser.setText(Session.getInstance().getCurrentUser().toString());
    }

    private void maximizeForm() {
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }
}
