/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.reservation;

import controller.Controller;
import domain.Reservation;
import form.reservation.model.TableModelReservation;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Vladan Simonovic
 */
public class FrmReservationList extends javax.swing.JPanel {

    Reservation reservationToSave = null;

    /**
     * Creates new form FrmReservationList
     */
    public FrmReservationList() {
        initComponents();
        prepareTableReservation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSaveAllReservations = new javax.swing.JButton();
        pnlReservations = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservationList = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Reservation list"));

        btnSaveAllReservations.setBackground(new java.awt.Color(255, 255, 255));
        btnSaveAllReservations.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSaveAllReservations.setForeground(new java.awt.Color(0, 153, 51));
        btnSaveAllReservations.setText("Save all reservations");
        btnSaveAllReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAllReservationsActionPerformed(evt);
            }
        });

        pnlReservations.setBorder(javax.swing.BorderFactory.createTitledBorder("Reservations"));

        tblReservationList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReservationList);

        javax.swing.GroupLayout pnlReservationsLayout = new javax.swing.GroupLayout(pnlReservations);
        pnlReservations.setLayout(pnlReservationsLayout);
        pnlReservationsLayout.setHorizontalGroup(
            pnlReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlReservationsLayout.setVerticalGroup(
            pnlReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSaveAllReservations))
                    .addComponent(pnlReservations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlReservations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveAllReservations)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveAllReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAllReservationsActionPerformed
        TableModelReservation model = (TableModelReservation) tblReservationList.getModel();

        try {
            List<Reservation> reservations = model.getReservations();
            if (reservations.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No reservations to save. Reservation list is empty.",
                        "Save all reservations", JOptionPane.ERROR_MESSAGE);
                
                return;

            }

//            for (Reservation reservation : reservations) {
//                reservationToSave = reservation;
//                long savedReservationID = Controller.getInstance().saveReservation(reservation);
//                System.out.println("Reservation is saved. Reservation ID: " + savedReservationID);
//            }
            Controller.getInstance().saveReservations(reservations);

            JOptionPane.showMessageDialog(this, "All reservations are saved!");
        } catch (Exception e) {
//            System.out.println("Could not make reservation for " + reservationToSave.getMember() + ".. It looks like reservation has already been made.");
            JOptionPane.showMessageDialog(this, e.getMessage(), "Save reservation error", JOptionPane.ERROR_MESSAGE);

        }
        model.setReservations(new ArrayList<>());
        model.fireTableDataChanged();
        
    }//GEN-LAST:event_btnSaveAllReservationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveAllReservations;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlReservations;
    private javax.swing.JTable tblReservationList;
    // End of variables declaration//GEN-END:variables

    private void prepareTableReservation() {
        TableModelReservation modelReservation = new TableModelReservation(new ArrayList<>());
        tblReservationList.setModel(modelReservation);
    }

    public JTable getTblReservationList() {
        return tblReservationList;
    }

}
